"use client";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/home/Navbar";
import { usePathname } from 'next/navigation';  // Use next/navigation for routing

const metadata: Metadata = {
  title: {
    absolute: "",
    default: "The Muslim Helpers Foundation",
    template: "%s | The Muslim Helpers Foundation",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();  // Get the current pathname

  const isAuthPage = pathname === '/register' || pathname === '/login' || pathname === '/forgot-password';

  return (
    <html lang="en">
      <head></head>
      <body>
        {!isAuthPage && <Navbar />} {/* Only show Navbar if not on auth pages */}

        {!isAuthPage && <main className="overflow-hidden" style={{ backgroundColor: 'rgba(252, 255, 246, 0.97)', minHeight: '100vh' }}>
          {children}
        </main>}
        {isAuthPage && <div >
          {children}
        </div>}
        {!isAuthPage && <Footer />} {/* Only show Footer if not on auth pages */}
      </body>
    </html>
  );
}
