import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "The Muslim Helpers Foundation",
    template: "%s | The Muslim Helpers Foundation",
  },
  description: "Generated by create next app",
};